### ISSUE TITLE
[Feature Request]: Support `hotpatching` for VMs

### ISSUE THREAD

**Issue by jkroepke** [cloudeteer/terraform-azurerm-vm#28]
### Feature Description

ref: 

* https://learn.microsoft.com/de-de/windows-server/get-started/enable-hotpatch-azure-edition
* https://learn.microsoft.com/de-de/windows-server/get-started/hotpatch

### Use Case

On a customer situation, we need `hotpatching` for all Azure VMs that we deploy.

On TF side, `hotpatching` is just an property which has dependency against other properties.

The important part is that `hotpatching` requires a special image. 

> Windows Server 2022 Datacenter: Azure Edition Hotpatch – Gen2

Is there an short image name availible as well?

### Privacy Statement

- [x] I agree

### Code of Conduct

- [x] I agree to follow this repository's Code of Conduct

**Comment by rswrz** [comment]
> Is there an short image name availible as well?

There is no URN alias for the image `Windows Server 2022 Datacenter: Azure Edition Hotpatch – Gen2`. Currently, URN aliases are only available for Azure “Getting Started” images, which can be listed using the command az vm image list.


However, you can create custom URN aliases. If `Windows Server 2022 Datacenter: Azure Edition Hotpatch – Gen2` is frequently used in your deployments, creating an alias makes sense. Otherwise, I recommend using the full image URN during deployment.

```hcl
image = "MicrosoftWindowsServer:WindowsServer:2022-datacenter-azure-edition-hotpatch"
```
